version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5555:5555"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mern-app

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5174:80"
    depends_on:
      - backend

volumes:
  mongo-data:
